In [1]:
#Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. 
#Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 


In [2]:
import numpy as np

In [7]:
array1 = np.arange(5)
array1.ndim

1

In [9]:
array2 = np.arange(8).reshape(4,2)
array2.ndim

2

In [19]:
array3 = np.arange(12).reshape(2,3,-1)
array3.ndim

3

In [20]:
array1

array([0, 1, 2, 3, 4])

In [21]:
array1[4]

4

In [22]:
array1[1:-2]

array([1, 2])

In [23]:
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
array2[1,0]

2

In [25]:
array2[1:,:3]

array([[2, 3],
       [4, 5],
       [6, 7]])

In [26]:
array3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [27]:
array3[1,2,0]

10

In [29]:
array3[0:,1:,-1]

array([[ 3,  5],
       [ 9, 11]])