In [26]:
import numpy as np

In [27]:
# İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. 
#Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

In [28]:
array1 = np.array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])
array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
array2 = np.array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])
array2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [30]:
#boyut
print(f"array1, {str(array1.ndim)} boyutludur.\narray2, {str(array2.ndim)} boyutludur.")

array1, 2 boyutludur.
array2, 3 boyutludur.


In [31]:
#eleman sayısı 
print(f"array1'in {str(array1.size)} tane elemanı vardır.\narray2'in {str(array2.size)} tane elemanı vardır.")

array1'in 30 tane elemanı vardır.
array2'in 30 tane elemanı vardır.


In [32]:
#satır sütun bilgileri
print(f"array1 {str(array1.shape[0])} satır, {str(array1.shape[1])} sütundan oluşur.")
print(f"array2 {str(array2.shape[0])} katman, {str(array2.shape[1])} satır ve {str(array2.shape[2])} sütundan oluşur.")

array1 5 satır, 6 sütundan oluşur.
array2 5 katman, 2 satır ve 3 sütundan oluşur.


In [33]:
#indexleme ve dilimleme(slicing) işlemleri
array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
array = [[1,2,3],[4,5,6]]

In [35]:
array1[1,3]

9

In [36]:
array1[:3,2:5]

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]])

In [37]:
array1[1:4,-1]

array([11, 17, 23])

In [38]:
array2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [39]:
array2[4,0,2]

26

In [40]:
array2[2,1,0]

15

In [41]:
array2[0:3,1:,0:2]

array([[[ 3,  4]],

       [[ 9, 10]],

       [[15, 16]]])